version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "monthly"
    groups:
      linters:
        patterns:
          - "husky"
          - "lint-staged"
          - "prettier"
